export const THINKING_WORDS = [
  'Analyzing context',
  'Pondering request',
  'Evaluating parameters',
  'Formulating plan',
  'Synthesizing thought',
  'Interpreting query',
  'Reviewing history',
  'Connecting dots',
  'Structuring response',
  'Gathering facts',
  'Processing ideas',
  'Drafting reply',
  'Considering options',
  'Weighing alternatives',
  'Computing logic',
  'Retrieving memory',
  'Aligning concepts',
  'Parsing meaning',
  'Tracing references',
  'Comparing approaches',
  'Refining structure',
  'Validating assumptions',
  'Extrapolating details',
  'Estimating impact',
  'Checking constraints',
  'Filtering noise',
  'Distilling essence',
  'Decoding intent',
  'Translating concepts',
  'Mapping relationships',
  'Assembling knowledge',
  'Organizing data',
  'Searching patterns',
  'Generating insights',
  'Preparing answer',
  'Optimizing output',
  'Formatting content',
  'Calibrating tone',
  'Polishing details',
  'Finalizing steps',
  'Unpacking logic',
  'Constructing meaning',
  'Resolving ambiguity',
  'Forming conclusion',
  'Structuring reasoning'
];

export const ICON_SUBSTITUTIONS: Record<string, string> = {
  'line-squiggle': 'brain',
  'loader-pinwheel': 'loader-2',
  gpu: 'cpu',
  'washing-machine': 'refresh-cw'
};