/**
 * Auto-generated. Embedded assets for the Nexus local CLI bridge:
 * the bundled `nexus` CLI plus the agent discovery artifacts the installer
 * writes to a machine-global location.
 *
 * DO NOT EDIT MANUALLY — regenerated by scripts/generate-cli-content.mjs.
 * Generated: 2026-07-17T20:21:09.631Z
 */

/** Combined content hash — used to detect and refresh a stale on-disk install. */
export const NEXUS_CLI_ASSETS_HASH = "a083c985933bf3a1";

/** Bundled standalone `nexus` CLI (written to <dataDir>/nexus-cli.js). */
export const NEXUS_CLI_JS = `#!/usr/bin/env node
"use strict";

// cli/nexus-cli.ts
var import_node_fs = require("node:fs");

// cli/mcpLineClient.ts
var import_node_net = require("node:net");
var McpLineClient = class {
  constructor(socketPath, opts = {}) {
    this.socketPath = socketPath;
    this.socket = null;
    this.nextId = 1;
    this.pending = /* @__PURE__ */ new Map();
    this.buffer = "";
    this.timeoutMs = opts.timeoutMs ?? 2e4;
  }
  connect() {
    return new Promise((resolve, reject) => {
      const socket = (0, import_node_net.createConnection)(this.socketPath);
      this.socket = socket;
      const onConnectError = (err) => {
        reject(new Error(
          \`Cannot connect to \${this.socketPath}: \${err.message}. Is Obsidian open with Nexus running for this vault?\`
        ));
      };
      socket.once("error", onConnectError);
      socket.once("connect", () => {
        socket.removeListener("error", onConnectError);
        socket.on("error", (err) => this.failAll(err));
        resolve();
      });
      socket.on("data", (chunk) => this.onData(chunk));
      socket.on("close", () => this.failAll(new Error("socket closed by server")));
    });
  }
  onData(chunk) {
    this.buffer += chunk.toString("utf8");
    let idx;
    while ((idx = this.buffer.indexOf("\\n")) >= 0) {
      const line = this.buffer.slice(0, idx).trim();
      this.buffer = this.buffer.slice(idx + 1);
      if (!line) continue;
      let msg;
      try {
        msg = JSON.parse(line);
      } catch {
        continue;
      }
      if (typeof msg.id === "number" && this.pending.has(msg.id)) {
        const p = this.pending.get(msg.id);
        this.pending.delete(msg.id);
        if (msg.error) {
          p.reject(new Error(\`\${msg.error.message} (JSON-RPC code \${msg.error.code})\`));
        } else {
          p.resolve(msg.result);
        }
      }
    }
  }
  failAll(err) {
    for (const p of this.pending.values()) p.reject(err);
    this.pending.clear();
  }
  request(method, params) {
    if (!this.socket) return Promise.reject(new Error("not connected"));
    const id = this.nextId++;
    const payload = JSON.stringify({ jsonrpc: "2.0", id, method, params }) + "\\n";
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        this.pending.delete(id);
        reject(new Error(\`Timeout after \${this.timeoutMs}ms waiting for "\${method}"\`));
      }, this.timeoutMs);
      this.pending.set(id, {
        resolve: (v) => {
          clearTimeout(timer);
          resolve(v);
        },
        reject: (e) => {
          clearTimeout(timer);
          reject(e);
        }
      });
      this.socket.write(payload);
    });
  }
  notify(method, params) {
    this.socket?.write(JSON.stringify({ jsonrpc: "2.0", method, params }) + "\\n");
  }
  async initialize() {
    const result = await this.request("initialize", {
      protocolVersion: "2025-06-18",
      capabilities: {},
      clientInfo: { name: "nexus-cli", version: "0.1.0" }
    });
    this.notify("notifications/initialized");
    return result;
  }
  listTools() {
    return this.request("tools/list", {});
  }
  callTool(name, args) {
    return this.request("tools/call", { name, arguments: args });
  }
  close() {
    this.socket?.end();
    this.socket?.destroy();
    this.socket = null;
  }
};

// cli/nexus-cli.ts
var IS_WIN = process.platform === "win32";
var NAME_PREFIX = "nexus_mcp_";
var UNIX_SOCK_DIR = "/tmp";
var UNIX_SUFFIX = ".sock";
var WIN_PIPE_DIR = "\\\\\\\\.\\\\pipe\\\\";
function sanitizeVaultName(name) {
  if (!name) return "";
  return name.toLowerCase().replace(/[^\\w\\s-]/g, "").replace(/\\s+/g, "-").replace(/-+/g, "-");
}
function vaultSocketPath(sanitized) {
  return IS_WIN ? \`\${WIN_PIPE_DIR}\${NAME_PREFIX}\${sanitized}\` : \`\${UNIX_SOCK_DIR}/\${NAME_PREFIX}\${sanitized}\${UNIX_SUFFIX}\`;
}
function listVaultSockets() {
  try {
    if (IS_WIN) {
      return (0, import_node_fs.readdirSync)(WIN_PIPE_DIR).filter((f) => f.startsWith(NAME_PREFIX)).map((f) => ({ name: f.slice(NAME_PREFIX.length), path: \`\${WIN_PIPE_DIR}\${f}\` }));
    }
    return (0, import_node_fs.readdirSync)(UNIX_SOCK_DIR).filter((f) => f.startsWith(NAME_PREFIX) && f.endsWith(UNIX_SUFFIX)).map((f) => ({ name: f.slice(NAME_PREFIX.length, -UNIX_SUFFIX.length), path: \`\${UNIX_SOCK_DIR}/\${f}\` }));
  } catch {
    return [];
  }
}
function resolveVault(requested) {
  const want = requested ?? process.env.NEXUS_VAULT ?? void 0;
  if (want) {
    const s = sanitizeVaultName(want);
    return { name: s, path: vaultSocketPath(s) };
  }
  const sockets = listVaultSockets();
  if (sockets.length === 1) return sockets[0];
  if (sockets.length === 0) {
    throw new Error("No open Nexus vaults found. Is Obsidian running with Nexus? Or pass --vault <name>.");
  }
  throw new Error(\`Multiple vaults open: \${sockets.map((x) => x.name).join(", ")}. Pass --vault <name>.\`);
}
function parseArgs(argv) {
  const positionals = [];
  const flags = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith("--")) {
      const key = a.slice(2);
      const next = argv[i + 1];
      if (next !== void 0 && !next.startsWith("--")) {
        flags[key] = next;
        i++;
      } else {
        flags[key] = true;
      }
    } else {
      positionals.push(a);
    }
  }
  return { positionals, flags };
}
function printToolResult(result, asJson) {
  if (asJson) {
    process.stdout.write(JSON.stringify(result, null, 2) + "\\n");
    return result.isError ? 1 : 0;
  }
  const text = (result.content ?? []).filter((c) => c.type === "text" && typeof c.text === "string").map((c) => c.text).join("\\n");
  const out = text || JSON.stringify(result, null, 2);
  if (result.isError) {
    process.stderr.write(out + "\\n");
    return 1;
  }
  process.stdout.write(out + "\\n");
  return 0;
}
var USAGE = \`nexus \\u2014 local CLI bridge to a running Nexus vault (no MCP config)

USAGE
  nexus tools [selector...]           Discover tools (getTools). Drill down as far as you want:
                                        nexus tools                     all agents (catalog)
                                        nexus tools storage             one agent's tools (compact)
                                        nexus tools storage list        one tool, full arg schema
                                        nexus tools "storage list, content read"   several tools at once
  nexus use "<command>" [context]    Execute a CLI-style tool command (useTools)
  nexus vaults                       List open Nexus vaults (live sockets)
  nexus doctor [--vault <name>]      Connect + handshake; print server info
  nexus --help                       This help

CONTEXT FLAGS (for \\\`use\\\`)
  --memory "<text>"      REQUIRED \\u2014 running summary of what you're doing
  --goal "<text>"        REQUIRED \\u2014 the objective of this call
  --workspace <id>       default: "default"
  --session <name>       default: "nexus-cli" (reuse one stable name per conversation)
  --constraints "<text>" optional
  --vault <name>         target a specific vault (else: single open vault, or NEXUS_VAULT)
  --json                 print raw JSON-RPC result

EXAMPLES
  nexus tools search
  nexus use "content read --path Daily/2026-07-17.md" --memory "auditing notes" --goal "read today's daily"
  nexus use "storage list" --vault "My Notes" --memory "smoke test" --goal "list vault root"
\`;
async function withClient(vaultName, fn) {
  const vault = resolveVault(vaultName);
  const client = new McpLineClient(vault.path);
  await client.connect();
  try {
    await client.initialize();
    return await fn(client);
  } finally {
    client.close();
  }
}
async function main() {
  const argv = process.argv.slice(2);
  const { positionals, flags } = parseArgs(argv);
  const cmd = positionals[0];
  const asJson = flags.json === true;
  const vaultFlag = typeof flags.vault === "string" ? flags.vault : void 0;
  if (!cmd || cmd === "help" || flags.help === true) {
    process.stdout.write(USAGE);
    return 0;
  }
  if (cmd === "vaults") {
    const sockets = listVaultSockets();
    if (sockets.length === 0) {
      process.stdout.write("No open Nexus vaults (no sockets in /tmp). Is Obsidian running?\\n");
      return 0;
    }
    for (const s of sockets) process.stdout.write(\`\${s.name}	\${s.path}
\`);
    return 0;
  }
  if (cmd === "doctor") {
    return withClient(vaultFlag, async (client) => {
      const tools = await client.listTools();
      process.stdout.write("OK \\u2014 connected, handshaked, tools/list responded.\\n");
      process.stdout.write(JSON.stringify(tools, null, 2) + "\\n");
      return 0;
    });
  }
  if (cmd === "tools") {
    const selector = positionals.slice(1).join(" ") || "--help";
    return withClient(vaultFlag, async (client) => {
      const result = await client.callTool("toolManager_getTools", {
        tool: selector,
        workspaceId: typeof flags.workspace === "string" ? flags.workspace : "default",
        sessionId: typeof flags.session === "string" ? flags.session : "nexus-cli",
        memory: typeof flags.memory === "string" ? flags.memory : "Discovering available Nexus tools.",
        goal: typeof flags.goal === "string" ? flags.goal : \`Inspect "\${selector}" tools.\`
      });
      return printToolResult(result, asJson);
    });
  }
  if (cmd === "use") {
    const command = positionals[1];
    if (!command) {
      process.stderr.write('Error: \`use\` needs a command string, e.g. nexus use "content read --path X" --memory .. --goal ..\\n');
      return 2;
    }
    const memory = typeof flags.memory === "string" ? flags.memory : "";
    const goal = typeof flags.goal === "string" ? flags.goal : "";
    if (!memory || !goal) {
      process.stderr.write("Error: --memory and --goal are REQUIRED (Nexus context contract).\\n");
      return 2;
    }
    const args = {
      tool: command,
      workspaceId: typeof flags.workspace === "string" ? flags.workspace : "default",
      sessionId: typeof flags.session === "string" ? flags.session : "nexus-cli",
      memory,
      goal
    };
    if (typeof flags.constraints === "string") args.constraints = flags.constraints;
    return withClient(vaultFlag, async (client) => {
      const result = await client.callTool("toolManager_useTools", args);
      return printToolResult(result, asJson);
    });
  }
  process.stderr.write(\`Unknown command "\${cmd}". Run \\\`nexus --help\\\`.
\`);
  return 2;
}
main().then((code) => process.exit(code)).catch((err) => {
  process.stderr.write(\`nexus: \${err.message}
\`);
  process.exit(1);
});
`;

/** SKILL.md for Claude Code (written to <dataDir>/skill/SKILL.md). */
export const NEXUS_SKILL_MD = `---
name: nexus
description: >-
  Read, search, and edit the user's Obsidian vault (notes, folders, canvas,
  tasks, memory/workspaces, saved prompts) from the shell via the \`nexus\` CLI —
  no MCP connection needed. Use whenever the user refers to their vault, notes,
  daily notes, second brain, or Obsidian, or asks you to find/read/change
  something stored there.
when_to_use: >-
  The task involves the user's Obsidian vault or notes and the \`nexus\` command
  is on PATH. Not for editing files in the current code repo — use normal file
  tools for those.
---

# Nexus vault CLI

\`nexus\` bridges the shell to a running Nexus (Obsidian) vault over a local
socket. Two steps: **discover**, then **use**.

## 1. Discover the tools you need (\`nexus tools\`)

\`nexus tools\` returns a live catalog. **Drill down to the narrowest thing you
need** — this keeps output small and gives you full argument schemas only for
the tools you'll actually call:

\`\`\`
nexus tools                          # all agents (overview)
nexus tools storage                  # one agent's tools (compact)
nexus tools storage list             # ONE tool, full arg schema  ← prefer this
nexus tools "storage list, content read"   # several tools at once
\`\`\`

Agents include: \`content\` (read/write/replace/insert notes), \`storage\`
(list/move/copy/archive files+folders), \`search\` (content/directory/memory),
\`canvas\`, \`task\`, \`memory\` (workspaces/states), \`prompt\`. Run \`nexus tools\`
once to see them all.

## 2. Run a tool (\`nexus use\`)

\`\`\`
nexus use "<agent action --flags>" --memory "<what you're doing>" --goal "<objective>"
\`\`\`

\`--memory\` and \`--goal\` are **required** (Nexus rejects calls without them).
Results are JSON on stdout.

\`\`\`
nexus use "content read --path Daily/2026-07-17.md" \\
  --memory "reviewing this week's notes" --goal "read today's daily note"

nexus use "search content --query 'context budget' --limit 5" \\
  --memory "auditing retrieval work" --goal "find notes about the budget service"
\`\`\`

## Choosing a vault

If exactly one vault is open, it's used automatically. If several are open,
\`nexus\` errors and lists them — run \`nexus vaults\` and add \`--vault <name>\`
(the human vault name works: \`--vault "My Notes"\`). You can also set
\`NEXUS_VAULT\` in the environment to pin one.

## Notes

- The search/list tools return **locations, not contents** — follow a hit with
  \`content read --path <path>\` to get the actual note.
- Reuse one stable \`--session "<name>"\` across a task so traces group together.
- If a command fails, run \`nexus --help\` or \`nexus tools <that tool>\` for the
  exact argument schema. If nothing connects, the vault's Obsidian window may be
  closed — ask the user to open it.
`;

/** AGENTS.md pointer block for Codex / skill-less agents. */
export const NEXUS_AGENTS_MD = `## Nexus vault access

This machine runs Nexus (Obsidian). To read, search, or edit the user's vault —
notes, folders, canvas, tasks, memory/workspaces, saved prompts — use the
\`nexus\` CLI. No MCP connection is needed.

- **Discover:** \`nexus tools [selector]\` returns the live tool catalog. Drill
  down to the narrowest selector you need — \`nexus tools storage list\` gives one
  tool with its full argument schema; \`nexus tools "storage list, content read"\`
  grabs several at once.
- **Execute:** \`nexus use "<agent action --flags>" --memory "<what you're doing>" --goal "<objective>"\`.
  \`--memory\` and \`--goal\` are **required** on every \`use\`. Results are JSON.
- **Vault:** one open vault is used automatically; if several are open, run
  \`nexus vaults\` and pass \`--vault <name>\` (or set \`NEXUS_VAULT\`).
- Search/list results are **locations, not contents** — follow a hit with
  \`content read --path <path>\`.

Run \`nexus --help\` for full usage. This applies to the user's Obsidian vault,
not files in the current code repository — use normal file tools for those.
`;
